name: 'quickcart'
version: '1.0.0'
config-version: 2

profile: 'quickcart'

model-paths: ["dbt/models"]
test-paths: ["dbt/tests"]
target-path: "target"
clean-targets:
  - "target"

models:
  quickcart:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
