version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - unique
          - not_null
      - name: country
        tests:
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: total_usd
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: price_usd
        tests:
          - not_null

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null

  - name: stg_sessions
    columns:
      - name: session_id
        tests:
          - unique
          - not_null
